### PR TITLE
First prototype of the adapter

### LINKED ISSUE #1: Numpy_Toolkit: prototype numpy adapter
#### Description:

Add a prototype of the `NumpyAdapter`. 
The plan is to wrap `numpy` around a `AdapterCompute` component in the UIs.

The project requires a few iterations to get it right, as we are experimenting with something new.

### PR DESCRIPTION
**Pull request by epignatelli**
Depends on: https://github.com/BHoM/BHoM_Engine/pull/1124
Depends on: https://github.com/BHoM/BHoM_UI/pull/120
Depends on: https://github.com/BHoM/Grasshopper_Toolkit/pull/393

   
### Issues addressed by this PR

Closes #1 

Initial prototype of the Numpy_Engine as a simply reflected library.
We are using the .Net bindings of the renown numpy library made by the guys at https://scisharp.github.io/SciSharp/ (very nice job). 

Not everything works, but the main components are there.
One thing that is annoying right now is that you cannot create an array from raw data.
The problem is that, if a method is generic, the back-end delegates of the UI components compile against its constraints, rather than the generic types themselves. See https://github.com/BHoM/BHoM_Engine/issues/1138 for more.

Note that, to call the [.Net port of numpy](https://github.com/SciSharp/Numpy.NET) this repo is using submodules. I preferred it to using nugets because we have more flexibility against the library, and add, remove or amend anything as we want. For example, I added a wrapper around the `[]` indexer operator with the `Slice` method.

If we were to use nuget we would be much more constrained to the pace of the development of SciSharp itself. 

What this means is that you need to use `pull recurse-submodules` to pull the submodules as well, and compile the `Numpy` project. Do unload all the projects in the solution file and build only `NUmpy`. I am sure there is a better solution to this, like embedding the project into the Numpy_Toolkit solution. I'll look into this later.

### Test files

[Get-Started.zip](https://github.com/BHoM/Numpy_Toolkit/files/3510030/Get-Started.zip)

### Changelog

- Add `External.Methods` to extract the methods to reflect into the UI
- Add `External.Constructors` to extract the constructors to reflect into the UI
- Wrap the `[]` indexer into a `Slice` method

### CODE REVIEW

**Comment by adecler** [comment]
Not sure I like your changes from yesterday. 
Personally, anything that doesn't compile after cloning is not something I like to see.
I think you are adding complexity to solve the exceptional circumstances you are facing now and would rather see a reference to a NuGet package in he long run.

**Comment by epignatelli** [comment]
Hi @adecler I agree with the nuget solution in the long term. At the moment I'd rather keep the submodules, waiting for the Numpy.net project to stabilise and us being more confident with the development model (pr to the Numpy.net repo?).

I added two things:
- Info on how to correctly clone or pull the repo in order to build it straight away
- The CI for the project. Note that the `Numpy` project is base on the `.Net Standard 2.0`, compared to our usual `.Net Framework 4.5.2`. `MSBuild` for Visual Studio 2015 fails with that, so I switched to Visual studio 2017.

**Comment by FraserGreenroyd** [comment]
Hi @epignatelli can you remove `Numpy_Toolkit` from the PR title ready for when this is reviewed and merged for the new guidelines :smile:

**Comment by epignatelli** [comment]
I just tested #3 by cloning the repo from scratch and it compiles correctly. Before closing #3 though, would you mind giving it a try as well?

**Comment by adecler** [comment]
OK, seems to be working for me now. 👍 
Better to have another person doing the same as I did that in a bit of a rush.

**Comment by epignatelli** [comment]
Ok! Thanks @adecler !
@tg359 would you mind trying to clone this repo using github desktop and doing nothing else than opening the `Numpy_Toolkit.sln` and compiling it?

**Pull request merged**
